### ISSUE TITLE
Broken link from install to import

### ISSUE THREAD

**Issue by mikejamesthompson** [mysociety/mapit.poplus.org#10]
The link at the bottom of [this page](http://mapit.poplus.org/docs/self-hosted/install/install-script/) is broken and should point to http://mapit.poplus.org/docs/self-hosted/import/. Shall I PR?

**Comment by dracos** [comment]
Sure, thanks!

**Comment by mikejamesthompson** [comment]
Don't seem to have permissions to push a branch ... can you add me?

**Comment by mikejamesthompson** [comment]
Ignore my previous comment, I figured it out :-)
