### ISSUE TITLE
Minor updates to the installation instructions

### ISSUE THREAD

**Issue by joesiltberg** [mysociety/mapit.poplus.org#12]
I've gone through the installation instructions and successfully got MapIt running in Debian Stretch.

I noticed a few minor issues:

* The git repository needs to be cloned recursively to get the theme submodule.
* Running migrate didn't prompt me for adding a super user.
* A couple of Markdown formatting issues.

Will create a PR shortly.

**Comment by dracos** [comment]
Fixed by #13, thanks!
